security:
    password_hashers:
        App\Entity\AdminUser:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_admin_user_provider:
            entity:
                class: App\Entity\AdminUser
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        login:
            pattern: ^/api/login$
            stateless: true
            provider: app_admin_user_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: app_admin_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/register$, roles: PUBLIC_ACCESS }
        - { path: ^/api/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/settings$, roles: PUBLIC_ACCESS }
        - { path: ^/api/navigation$, roles: PUBLIC_ACCESS }
        - { path: ^/api/pages, roles: PUBLIC_ACCESS }
        - { path: ^/api/services$, roles: PUBLIC_ACCESS }
        - { path: ^/api/reservation-requests$, roles: PUBLIC_ACCESS }
        - { path: ^/api/contact$, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
